export const answers = [
  "aardvarks",
  "Master P",
  "A DVD of Cool Runnings",
  "Turtles",
  "TV shows that debuted in 1983",
  "Cadbury eggs with alternate color insides",
  "Cat videos",
  "Blaster Master for NES Walkthrough",
  "Dino Bravo",
  "Who was the 22nd President of the United States?",
  "Does Canada have Sonic restaurants?",
  "pineapples",
  "Why is Bill Simmons long-winded at times, but still funny?",
  "Where is Gilligan's Island actually located?",
  "Movies with Shaq in them",
  "Movies without Shaq in them",
  "Ken Griffey video game appearances",
  "Something called Honey Boo Boo Child",
  "Tom Arnold",
  "The 1996 Championship trophy George Costanza broke",
  "Shark Attack fruit snacks, where to get them",
  "Lunchables",
  "Ohio fish tank providers",
  "Lime green Randy Moss throwbacks",
  "2012 Red Sox playoff schedule",
  "Highest altitude in Wichita",
  "Hologram 2Pac tour dates",
  "Weird Al fan sites",  // Note: The same number 27 was used twice, so this is merged with 27
  "Joe Montana singing back up with Huey Lewis live",
  "What is a pay phone anyway?",
  "Why was Spider-Man 3 such a bad movie? 1 and 2 were decent",
  "Swedish Lakes",
  "My personal Kevin Bacon number",
  "New copies of Office Space on VHS",
  "Pete and Pete season 3",
  "Larry Bird YouTube videos",
  "How to get past the bat in Willy Beamish",
  "Interesting facts about John Kruk",
  "Pavement Slanted and Enchanted tumblrs",
  "Full House 25th anniversary celebrations",
  "The uncola",  // Note: The same number 39 was used twice, so this is merged with 39
  "iOS6 Map of Waldo's location",
  "How much coffee is enough?",
  "Reviews of anything starring Ben Affleck",
  "Is this real life?",
  "Friends spin-offs",
  "Green Power Ranger bio",
  "Did Nolan Bushnell really found Chuck E. Cheese?",
  "Trapper Keepers",
  "Woodchucks",
  "Baby from the show Dinosaurs",
  "Antiques Hollywood, FL",
  "bus stops Renton",
  "Truman Burbank"
];